MetaCell/sckan-composer

backend/composer/enums.py, backend/composer/services/export_services.py
According to [SCKAN-129 ](https://metacell.atlassian.net/browse/SCKAN-129)
Test export example:
[export_2023-06-14_09-06-09.csv](https://github.com/MetaCell/sckan-composer/files/11743998/export_2023-06-14_09-06-09.csv)
=> SCKAN-129 untangle relationship-predicate at export

backend/composer/services/export_services.py
[export_2023-06-14_15-43-49.csv](https://github.com/MetaCell/sckan-composer/files/11747947/export_2023-06-14_15-43-49.csv)
=> SCKAN-129-b add column predicate to export file

backend/composer/enums.py, backend/composer/services/export_services.py
Also pushing export relationship for destination and via type.
=> Fix export: skip projection and fcr phenotype rows if none

frontend/src/components/CheckForDuplicates/CheckDuplicatesDialog.tsx
closes https://metacell.atlassian.net/browse/SCKAN-145
- Updates UI to allow searches with either (or both) source or destination entities set.
https://github.com/MetaCell/sckan-composer/assets/19196034/69558475-8118-44b5-b819-99b903b034cd
=> SCKAN-145 feat: Allow check for duplicates with just one AnatomicalEntity set

backend/composer/api/filtersets.py
Closes https://metacell.atlassian.net/browse/SCKAN-144
- Adds a custom filter strategy Anatomical Entities. 
This new strategy consists in searching individually by each word in the search string and intersect the results. (making the order of the words in the search string irrelevant)
https://github.com/MetaCell/sckan-composer/assets/19196034/7327f2b5-3d2f-4aa1-9656-cc72588091be
=> SCKAN-144 feat: Update Anatomical Entity search

frontend/src/components/Forms/StatementForm.tsx
* Fixing typos
* fixing one more typo
=> Feature/typos 1.0.1 (#166)

frontend/src/components/Forms/StatementForm.tsx, frontend/src/components/ProofingTab/SortableItem.tsx, frontend/src/components/Widgets/ArrayFieldTemplate.tsx
ensure that at least one destination is always present (remove the bin icon if there is only one destination).
=> #199 destination improvements

frontend/src/components/Forms/StatementForm.tsx, frontend/src/components/ProofingTab/PathsBuilder.tsx, frontend/src/components/ProofingTab/SortableItem.tsx, frontend/src/components/Widgets/ArrayFieldTemplate.tsx
fix loading problem
hide drag and drop for destinations
=> #198 fix loading problem, hide drag and drop for destinations

frontend/src/components/ProofingTab/GraphDiagram/Widgets/CustomLinkWidget.tsx, frontend/src/components/ProofingTab/GraphDiagram/Widgets/DestinationNodeWidget.tsx, frontend/src/components/ProofingTab/GraphDiagram/Widgets/OriginNodeWidget.tsx, frontend/src/components/ProofingTab/GraphDiagram/Widgets/ViaNodeWidget.tsx, frontend/src/components/icons.tsx
=> #201 statement display styling

backend/composer/admin.py
closes https://metacell.atlassian.net/jira/software/c/projects/SCKAN/boards/22?selectedIssue=SCKAN-246
=> feat(admin): added date_hierarchy for KS

backend/composer/api/serializers.py, backend/composer/models.py
Jira Link - [SCKAN-247](https://metacell.atlassian.net/browse/SCKAN-247)
Task description:
- changes text as requirements
- do not show the laterality statement when laterality is unknown or not-specified. 
https://github.com/MetaCell/sckan-composer/assets/59233227/e9fa5961-7e74-41ea-81a2-fa2241bdb9f7
[SCKAN-247]: https://metacell.atlassian.net/browse/SCKAN-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature/sckan-247: Statement preview improvements

frontend/src/components/ProofingTab/PathsBuilder.tsx, frontend/src/theme/Theme.tsx
Fixing the Destinations selector in the Proofing tab as per https://github.com/MetaCell/sckan-composer/pull/190/commits/31878394cd0806992109f8cd744d2d124eeafaaf 
@Salam-Dalloul @ddelpiano
=> SCKAN-235 Fixing Destination selector

frontend/src/components/Topbar.tsx
=> #243 change logout button

backend/composer/api/permissions.py, backend/composer/api/views.py, frontend/src/components/Forms/FormBase.tsx
Closes - [SCKAN-256](https://metacell.atlassian.net/browse/SCKAN-256)
Backend
- Add a permission class to check if the state is EXPORTED in Connectivity Statement
Frontend
- Change the value of the form/localData only when the UPDATE API is successful. 
[SCKAN-256]: https://metacell.atlassian.net/browse/SCKAN-256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature/256 - Permissions changes for the export state in Connectivity statement

backend/composer/services/cs_ingestion/cs_ingestion_services.py
closes https://metacell.atlassian.net/browse/SCKAN-248
As requested by @ddelpiano, this PR changes the behaviour of the ingestion to add a note with the invalid reasons even if the state was already Invalid:
=> SCKAN-248 feat: Add invalid note even if CS was in invalid state already

backend/composer/services/export_services.py
- Adds URI column to exported csv
[Example export file](https://docs.google.com/spreadsheets/d/12K1BLCvVY3dCOWqyIqQUeDOy6uxaqtVseP_KD4qQp1o/edit?usp=sharing)
=> feat: Add URI to exported csv

backend/composer/services/export_services.py
- Adds connected from URI column to exported csv
- Changes connected from column separator from , to ;
[example exported file](https://docs.google.com/spreadsheets/d/1XItttWLTffnyVxxZkcJb1Jr9uJq3XyUsIp293flcNr8/edit?usp=sharing)
=> feat: Add connected from uri to exported csv

backend/composer/services/state_services.py
Jira Link - [SCKAN-289](https://metacell.atlassian.net/browse/SCKAN-289)
[SCKAN-289]: https://metacell.atlassian.net/browse/SCKAN-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Remove check for phenotype in ConnectivityStatementStateService

frontend/src/services/GraphDiagramService.ts
Closes https://metacell.atlassian.net/browse/SCKAN-326
- Adds nodes without a  (direct or indirect)  path to a destination as disconnected nodes
=> SCKAN-326 feat: Add disconnected nodes to graph

backend/composer/api/serializers.py
Closes https://metacell.atlassian.net/browse/SCKAN-386
Sets `data['connectivity_statement_id']` to be the primary key (opposed to the complete object) in all the following scenarios:
- Create statement alert
- Update statement alert
- Delete statement alert
- Updating statement with at least 1 statement alert
- Updating statement without statement alerts
=> SCKAN-386 fix: Fix statement alert serialization

backend/composer/services/cs_ingestion/helpers/changes_detector.py, backend/composer/services/cs_ingestion/helpers/getters.py, backend/composer/services/cs_ingestion/helpers/statement_helper.py, backend/composer/services/cs_ingestion/neurondm_script.py
Task description:
- Function get_populationset_from_neurondm_id extracts the population set from the statement ID using regular expressions.
- Handles cases for /sparc-nlp/ and /readable/ URIS.
- update `get_or_create_neurondm_populationset` to get population_name from neurondm
=> Feature/sckan-394-ingestion - update ingestion and statement helper to add populationset on ingestion

frontend/src/services/GraphDiagramService.ts
as per title, the goal is to display the same entity if used as origin/via/destination multiple times with different node types.
=> Refactored graph service

backend/composer/api/filtersets.py, backend/tests/test_population_name_util.py
=> fixing sorting by owner for statements

backend/composer/api/filtersets.py
https://metacell.atlassian.net/browse/SCKAN-408?focusedCommentId=17950
=> adding sorting method for KS

backend/composer/models.py
Closes https://metacell.atlassian.net/browse/SCKAN-418
The ordering now works as follows:
1. User changes other of 1 via.
2. Other via instances are re-ordered to maintain a contiguous sequence.
3. After reordering, the system checks whether the current Via and any affected Vias still **explicitly** reference valid from_entities: If **any** from_entity is no longer available (i.e., it now comes after the Via), the from_entities of that via is cleared; otherwise we kept it as it is:
https://github.com/user-attachments/assets/7d641685-2a96-4c15-add1-c8fd586bc9ad
=> SCKAN-418 feat: Retain from selection when changing the order in the path builder

applications/composer/frontend/src/components/Forms/StatementForm.tsx
https://github.com/user-attachments/assets/3e90285e-b435-4adf-8108-f17e2808d481
=> fix options issue

applications/composer/backend/requirements.txt
=> fix: Bump django-admin-sortable2 version
