frontend/src/Pages/StatementDetails.tsx
frontend/src/components/DistillationTab.tsx
frontend/src/components/Forms/ProvenanceForm.tsx
frontend/src/components/ProofingTab/PathsBuilder.tsx
frontend/src/components/ProofingTab/ProofingTab.tsx
frontend/src/components/SentenceStatementWithDois.tsx
frontend/src/components/TriageStatementSection/TriageStatementSection.tsx
frontend/src/components/Widgets/NotesFomList.tsx
frontend/src/styles/styles.ts

[SCKAN-137](https://metacell.atlassian.net/browse/SCKAN-137)
SCKAN-137 replace details section for accordion at statement details page
SCKAN-137 add other ks section at the bottom of statement details page
SCKAN-137 only show other ks section if any
SCKAN-137 move NLP sentence to the bottom of statement details page
https://github.com/MetaCell/sckan-composer/assets/82731550/64806657-5b86-41e7-ab33-865ee2c91f48
[SCKAN-137]: https://metacell.atlassian.net/browse/SCKAN-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCKAN-137 change details layout at statement details page

---

frontend/src/components/Widgets/CustomAutocompleteForwardConnection.tsx

Issue #SCKAN-182
Problem: 'Clear search' button does nothing
Solution: 
In order to solve this there should be state to control input value, so I added this state. 
This inputValue depends on searchValue if it is empty or has some value so, in order to clear search, I added listener function, which sets search value to an empty string whenever this 'clear search' button is clicked.
here is the video of the solution
https://github.com/MetaCell/sckan-composer/assets/67194168/ee52ee94-5d1a-47df-b877-ffc4b70823f6

SCKAN-182 'Clear search' button does nothing

---

backend/composer/services/cs_ingestion/cs_ingestion_services.py

Should fix:
```
[2024-02-07 18:46:52,422] -    DEBUG -       neurondm -          core.py:939  - [OntId('NIFRAW:neurons/ttl/phenotype-core.ttl'), OntId('NIFRAW:neurons/ttl/phenotype-indicators.ttl'), OntId('NIFRAW:neurons/ttl/phenotypes.ttl')]
ERROR:root:Ingestion aborted due to null value in column "anatomicalentity_id" of relation "composer_connectivitystatement_origins" violates not-null constraint
DETAIL:  Failing row contains (5358, 261, null).
```
I couldn't replicate the error locally, in the sense it was not causing the ingestion to fail, but I believe the following case was the problem:
The above should no longer be possible (also applies to the vias and destinations)

SCKAN-248 fix: Add check for anatomical entity before adding it

---

backend/composer/services/cs_ingestion/neurondm_script.py

closes https://metacell.atlassian.net/browse/SCKAN-248
(https://metacell.atlassian.net/browse/SCKAN-248?focusedCommentId=13730)
- Empties the from_entities set on the vias/destinations created from neuronDM when applicable (from entities set equal to previous layer anatomical entities)

SCKAN-248 feat: Update from_entities when applicable

---

backend/composer/services/cs_ingestion/cs_ingestion_services.py
backend/composer/services/cs_ingestion/helpers.py

Updates ingestion based after changes from https://metacell.atlassian.net/browse/SCKAN-250.
- Removes references to the no longer available CircuitType.UNKNOWN

SCKAN-250 fix: Remove CircuitType.UNKNOWN from ingestion

---

backend/composer/models.py

Closes https://metacell.atlassian.net/browse/SCKAN-282
The authorization check is done [here](https://github.com/MetaCell/sckan-composer/blob/feature/SCKAN-282/backend/composer/services/state_services.py#L153)
https://github.com/MetaCell/sckan-composer/assets/19196034/3ca3adb1-ea13-4532-a4fb-0d81ef406152

SCKAN-282 feat: Allow transition from Exported to Compose Now

---

backend/composer/api/serializers.py
backend/composer/models.py
backend/composer/services/graph_service.py
frontend/src/components/ProofingTab/ProofingTab.tsx
frontend/src/components/Widgets/CustomEntitiesDropdown.tsx

frontend styling and some journey improvements

---

backend/backend/settings.py
backend/composer/api/handlers.py
backend/composer/api/serializers.py
backend/composer/apps.py
frontend/src/apiclient/backend/api.ts
openapi/openapi.yaml

jira Link - update on -> https://metacell.atlassian.net/browse/ESCKAN-35
- add reference_uri to KnowledgeStatement endpoint response 
- Corrected the serializer to_representation for KS-serializer - `super(ConnectivityStatementSerializer, self).to_representation(instance)`
- Added CORS to `/api/composer/knowledge-statement/` using [django-cors-header's signals](https://github.com/adamchainz/django-cors-headers?tab=readme-ov-file#signals).

Feature/esckan-35 -  KnowledgeStatement endpoint fixes

---

backend/requirements.txt

Update requirements to add django-cors-headers==4.3.1

ESCKAN-35 add cors requirement txt

---

backend/composer/api/serializers.py

Add additional fields to the public KS endpoint. Newly added fields are -             
"provenances",
"knowledge_statement",
"journey",
"laterality",
"projection",
"circuit_type",
"sex",
"apinatomy_model",
"statement_preview",
Video demo:
https://github.com/MetaCell/sckan-composer/assets/59233227/6f833aca-5962-486e-b31f-f5aa5129d705

Feature/esckan 35 - add additional fields to the public KS endpoint

---

backend/composer/admin.py
backend/composer/api/serializers.py
backend/composer/api/urls.py
backend/composer/api/views.py
backend/composer/models.py
frontend/src/apiclient/backend/api.ts
frontend/src/components/Forms/StatementForm.tsx
frontend/src/components/TriageStatementSection/StatementDetailsAccordion.tsx
frontend/src/index.tsx
frontend/src/services/ProjectionService.tsx
openapi/openapi.yaml

Jira ticket - [SCKAN-293](https://metacell.atlassian.net/browse/SCKAN-293)
Task description:
1. Update serializer, viewset, and router - to avail ProjectionPhenotype.
2. Generate the openapi spec.
3. Replace projection phenotype instead of projection (from enum) in the FE 
4. remove projection from admin - so user can only add projection phenotype in the admin panel.
Video demo
https://github.com/MetaCell/sckan-composer/assets/59233227/01188665-82a4-45ce-a68b-ac0633e13ec7
[SCKAN-293]: https://metacell.atlassian.net/browse/SCKAN-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature/csckan-293 - Front end Projection Phenotypes do not reflect Projection phenotypes specified in Admin table

---

backend/composer/api/serializers.py
backend/composer/models.py
backend/composer/services/graph_service.py
backend/tests/test_journey.py
frontend/src/apiclient/backend/api.ts
openapi/openapi.yaml

- Added a new serializer field - `entities_journey`. This returns all the vias, destinations, and origins of that respective KS. 
- 
```
it is of the form:
entitiesJourney: EntitiesJourneyType[]
where EntitiesJourneyType  is;
export type EntitiesJourneyType = {
origins: string[];
vias: string[];
destinations: string[];
};
```
- Each string in origin, vias, destination - is the name of that origin/via/destination.
- We get this information from the - [consolidated_paths](https://github.com/MetaCell/sckan-composer/blob/82c22ad198728d48113d554bfed688dc0b350f0f/backend/composer/services/graph_service.py#L91).

Feature/esckan-65 - get entities (origin, destination, vias) in the journey as part of serializer export

---

frontend/src/services/GraphDiagramService.ts

Closes https://metacell.atlassian.net/browse/SCKAN-300
Specifically:
>However the changes in their connections do not get saved
Solution: 
We make it impossible to change the links by locking them.

CSCKAN-300 feat: Lock links

---

frontend/src/Pages/SentenceDetails.tsx
frontend/src/components/Forms/SentenceForm.tsx
frontend/src/helpers/ownershipAlert.ts
frontend/src/services/SentenceService.ts

Updated the NLP logic to handle ownership, addressing feedback from [PR #342 discussion](https://github.com/MetaCell/sckan-composer/pull/342#discussion_r1824422388). Additionally, modified the UI components so that the disabled state now reflects the sentence status rather than ownership.

update NLP sentence form check

---

frontend/src/components/Forms/StatementForm.tsx

closes https://metacell.atlassian.net/browse/SCKAN-342
- Refreshes statement after creating vias/destinations
https://github.com/user-attachments/assets/735fb9d0-5624-44a5-9e52-0cf276e0c88f

SCKAN-342 fix: Refresh statement after via/destination creation

---

backend/composer/models.py
backend/composer/services/cs_ingestion/helpers/notes_helper.py
backend/composer/services/cs_ingestion/helpers/statement_helper.py

Jira ticket - [SCKAN-273](https://metacell.atlassian.net/browse/SCKAN-273)
About the issue - of statements getting converted from exported to invalid and vice versa. 
Previously:
`ConnectivityStatement.objects.filter(reference_uri=reference_uri).update(**defaults)`
IMO - we should not update the [default state](https://github.com/MetaCell/sckan-composer/blob/79c5ff869fcf3e39f53e8345e50a1acb739a933f/backend/composer/services/cs_ingestion/helpers/statement_helper.py#L22) here (since the default state is [EXPORTED](https://github.com/MetaCell/sckan-composer/blob/79c5ff869fcf3e39f53e8345e50a1acb739a933f/backend/composer/services/cs_ingestion/helpers/statement_helper.py#L22)). So the problem we were facing - happened because if the statement had any changes, then - it was getting [converted to …

Feature/sckan-273 

---

backend/composer/services/cs_ingestion/neurondm_script.py

Inspired from [SCKAN-273](https://metacell.atlassian.net/browse/SCKAN-273) discussions. Specify notes that are coming from neurondm by prefixing - "Neurondm: " before the note. 
[SCKAN-273]: https://metacell.atlassian.net/browse/SCKAN-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCKAN-273 - specify system admin notes coming neurondm

---

backend/composer/api/serializers.py
backend/composer/api/views.py
frontend/src/apiclient/backend/.openapi-generator/FILES
frontend/src/services/StatementService.ts

closes https://metacell.atlassian.net/browse/SCKAN-323
Error explained:
- The frontend was making an update request that included a change of owner.
- The backend applied the change and then ran into a permission error on a post processing step
Solution:
- This PR changes the frontend request to include the correct/desired owner for the statement
- It also refactors the backend to move the update logic from the view to the serializer.
- Makes the owner and owner_id read_only on the update and provides a more descriptive error message when those are included in the incoming request
https://github.com/user-attachments/assets/7c022c2d-2d14-46f5-9190-9ac39a17dc73

SCKAN-323 fix: Update frontend to send new owner_id on retry

---

backend/composer/services/layers_service.py

Closes https://metacell.atlassian.net/browse/SCKAN-373
Adds missing service file from https://github.com/MetaCell/sckan-composer/pull/394

SCKAN-373 fix: Add missing service file

---

backend/backend/settings.py
frontend/src/apiclient/backend/api.ts
frontend/src/components/Forms/StatementForm.tsx
frontend/src/components/ProofingTab/GraphDiagram/Models/CustomNodeModel.tsx
frontend/src/components/ProofingTab/GraphDiagram/Widgets/DestinationNodeWidget.tsx
frontend/src/components/ProofingTab/GraphDiagram/Widgets/ViaNodeWidget.tsx
frontend/src/services/GraphDiagramService.ts
openapi/openapi.yaml

- Uses [ENUM_NAME_OVERRIDES](https://drf-spectacular.readthedocs.io/en/latest/faq.html#i-get-warnings-regarding-my-enum-or-my-enum-names-have-a-weird-suffix) to specify the enum names.
- Updates frontend imports to use the new enum names

refactor: Rename enum types

---

backend/composer/management/commands/update_connectivity_statement_field.py
backend/composer/models.py
backend/composer/services/cs_ingestion/neurondm_new_field_ingestion_service.py

Potentially closes: https://metacell.atlassian.net/browse/SCKAN-404
- Updates update_connectivity_statement_field to allow transforms and skip model validation.
- Fixes small bug on population set validation on save
Running:
`python manage.py update_connectivity_statement_field --cs_field population --neurondm_field populationset --skip_validation --transform_fn composer.services.cs_ingestion.helpers.getters.get_or_create_populationset`
Should update all connectivity statements with the populationset defined by neurondm independently of the statement condition

SCKAN-404 feat: Update update connectivity statement command

---

frontend/src/components/ProofingTab/GraphDiagram/Widgets/ViaNodeWidget.tsx

I changed some of the vias type in the demo data to make them sensory axon
```jsx
[via.type for via in cs.via_set.all()]
['SENSORY_AXON', 'SENSORY_AXON', 'SENSORY_AXON', 'SENSORY_AXON', 'AXON', 'AXON', 'SENSORY_AXON', 'SENSORY_AXON', 'SENSORY_AXON']
```
Demo of how it looks

SCKAN-411 - update anatomicalType label in ViaNodeWidget to include 'Axon to PNS'

---

applications/composer/backend/composer/management/commands/ingest_statements.py
applications/composer/backend/composer/services/cs_ingestion/cs_ingestion_services.py
applications/composer/backend/composer/services/cs_ingestion/helpers/overwritable_helper.py
applications/composer/backend/tests/test_ingest_statements.py

Closes https://metacell.atlassian.net/browse/SCKAN-443
- Adds a new population_file optional argument to the ingest statements command (expects it to be a filepath to a file that stores population ids, 1 per line.
- Updates ingestion service to consider populations with the id in the population_file as can_be_overwritten, independently of their state.
- Adds proper unit tests for this specific feature
https://github.com/user-attachments/assets/20d92a41-9e45-4480-8f7c-523abdf7f45e

SCKAN-443 feat: Add population_file param to ingest_statements

---

applications/composer/backend/composer/models.py
applications/composer/frontend/src/components/Forms/ProvenanceForm.tsx

Closes https://metacell.atlassian.net/browse/SCKAN-434?focusedCommentId=24111
As far as I'm aware there's no perfect regex to match doi so it's possible that we can still have some invalid ones; with that said, I updated the regex to be a bit more rigid and specifically prevent double slashes

SCKAN-434 fix: Make doi regex more rigid
